import { access, cp, mkdir, readFile, readdir, rm, writeFile } from 'node:fs/promises';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..');
// WF_DIST_DIR lets verification build into an isolated directory so it cannot
// contend with the live dev loop rebuilding dist/ (see tests/build.test.mjs).
const dist = process.env.WF_DIST_DIR ? resolve(process.env.WF_DIST_DIR) : resolve(root, 'dist');
const manifest = JSON.parse(await readFile(resolve(root, 'manifest.json'), 'utf8'));

// nativeMessaging is how the extension asks the OS tailscale client who the
// tailnet is: tailscaled is only reachable via its unix socket, and a browser
// cannot open one. The host is a read-only `tailscale status` reader.
const exactPermissions = ['activeTab', 'contextMenus', 'nativeMessaging', 'scripting', 'sidePanel', 'storage'];
const actualPermissions = [...(manifest.permissions ?? [])].sort();
if (JSON.stringify(actualPermissions) !== JSON.stringify(exactPermissions)) {
  throw new Error(`manifest permissions must equal ${exactPermissions.join(', ')}`);
}
if ('content_scripts' in manifest) throw new Error('content scripts are forbidden in the MVP');
// Static host permissions: exactly THIS DEVICE's origins (operator requirement
// 2026-09-27 — discovery is automatic and attaching is one click, so no address
// is ever typed). Least-privilege preserved: loopback, this device's crosvm veth
// bridge, its UIAI bridge and this device's own tailnet node. Any other network
// peer still needs that one origin granted on connect.
// 127.0.0.1:41112 is the Tailscale LocalAPI: it is how the tailnet tells the
// extension who its peers are. Loopback, one port, no remote host.
// 100.94.238.56 / 100.69.132.82 are the estate's own tailnet nodes (AGENTS.md),
// granted so the authoritative daemon connects with no prompt at all; any other
// tailnet peer is discovered and granted on connect, one click, that origin only.
const localOrigins = ['http://127.0.0.1/*', 'http://127.0.0.1:41112/*', 'http://localhost/*', 'http://100.115.92.26/*', 'http://100.115.92.26:7456/*', 'http://100.127.113.90/*', 'http://100.94.238.56/*', 'http://100.69.132.82/*'];
if (JSON.stringify([...(manifest.host_permissions ?? [])].sort()) !== JSON.stringify([...localOrigins].sort())) {
  throw new Error(`host permissions must be exactly ${localOrigins.join(', ')} (local daemon origins only)`);
}
const optional = [...(manifest.optional_host_permissions ?? [])].sort();
if (JSON.stringify(optional) !== JSON.stringify(['http://*/*', 'https://*/*'])) {
  throw new Error('optional host permissions must be bounded to http(s) origins');
}
if (manifest.background?.service_worker !== 'background.mjs') {
  throw new Error('background service worker must be background.mjs');
}
if (manifest.side_panel?.default_path !== 'sidepanel.html') {
  throw new Error('side panel entry must be sidepanel.html');
}
if (manifest.chrome_url_overrides?.newtab !== 'startpage.html') {
  throw new Error('new tab entry must be startpage.html');
}

await rm(dist, { recursive: true, force: true });
await mkdir(dist, { recursive: true });
await writeFile(resolve(dist, 'manifest.json'), `${JSON.stringify(manifest, null, 2)}\n`);

// Copy the plain MV3 sources. The Workforce full page is a built artifact, so
// its Svelte source tree is excluded from the shipped extension.
const staticEntries = await readdir(resolve(root, 'src'), { withFileTypes: true });
for (const entry of staticEntries) {
  // The Workforce full page is a built artifact (Vite), not a shipped source.
  if (entry.name === 'workforce') continue;
  await cp(resolve(root, 'src', entry.name), resolve(dist, entry.name), { recursive: true });
}

// Stamp the packaged build identity, so any surface can show which build the
// browser is actually running (docs/17 §4: footer / advanced meta only).
{
  const { execFileSync } = await import('node:child_process');
  // Commit identity, not a wall-clock timestamp: the build must stay
  // byte-deterministic, and the commit already identifies a build uniquely.
  let sha = 'unknown';
  let committedAt = null;
  try {
    sha = execFileSync('git', ['rev-parse', '--short', 'HEAD'], { cwd: root, encoding: 'utf8' }).trim();
    committedAt = execFileSync('git', ['log', '-1', '--format=%cI'], { cwd: root, encoding: 'utf8' }).trim();
    // The build happens before the commit that carries it, so HEAD alone would
    // name the PREVIOUS commit. A dirty tree is stated plainly rather than
    // stamped with a revision that does not contain this code.
    const dirty = execFileSync('git', ['status', '--porcelain', '--', 'src', 'manifest.json', 'scripts'], { cwd: root, encoding: 'utf8' }).trim();
    if (dirty) sha = `${sha}-dirty`;
  } catch { /* not a checkout */ }
  const stamp = [
    '/** Packaged build identity. Generated by scripts/build.mjs - do not edit. */',
    `export const BUILD = Object.freeze({ sha: ${JSON.stringify(sha)}, committedAt: ${JSON.stringify(committedAt)} });`,
    '',
  ].join('\n');
  await writeFile(resolve(dist, 'lib', 'build-info.mjs'), stamp);
}

// Bundle the workforce full page when the toolchain is installed. A missing
// toolchain degrades to a build without the page; a real bundling failure is
// an error (never silently shipped as "absent").
let uiBundled = false;
let hasVite = true;
try {
  await access(resolve(root, 'node_modules/vite/package.json'));
} catch {
  hasVite = false;
}
if (!hasVite) {
  console.warn('WARN: vite toolchain absent; workforce.html not bundled (run npm install)');
} else {
  const { build } = await import('vite');
  await build({ configFile: resolve(root, 'vite.config.mjs'), logLevel: 'warn' });
  const built = await readFile(resolve(dist, 'workforce.html'), 'utf8');
  if (!/workforce-assets\//.test(built)) throw new Error('workforce.html was built without its bundled assets');
  await rm(resolve(dist, 'src'), { recursive: true, force: true });
  uiBundled = true;
}

// ── White-label: brand substitution from FOCUSA_BRAND (default Focusa Workforce). ──
const brand = process.env.FOCUSA_BRAND || 'Focusa Workforce';
const brandU = brand.toUpperCase();
const chip = brand.trim().charAt(0).toUpperCase();
const repls = [
  [/Focusa Workforce Chrome/g, `${brand} Chrome`],
  [/Focusa Workforce/g, brand],
  [/FOCUSA WORKFORCE/g, brandU],
  [/aria-hidden="true">F<\/div>/g, `aria-hidden="true">${chip}</div>`],
  [/<span class="mark">F<\/span>/g, `<span class="mark">${chip}</span>`],
];
let touched = 0;
for (const ent of await readdir(dist, { recursive: true })) {
  if (!ent.endsWith('.html') && !ent.endsWith('.mjs')) continue;
  // Never rewrite the hashed bundle/asset output: it is generated, and brand
  // text there comes from the source at bundle time.
  if (ent.startsWith('workforce-assets')) continue;
  const p = resolve(dist, ent);
  const txt = await readFile(p, 'utf8');
  let out = txt;
  for (const [re, to] of repls) out = out.replace(re, to);
  if (out !== txt) { await writeFile(p, out); touched++; }
}
console.log(`PASS: built ${brand} MV3 unpacked extension at ${dist} (${touched} files re-branded${uiBundled ? ', workforce page bundled' : ''})`);

// ── Public demo: FOCUSA_PUBLIC_NEWTAB=1 makes the default new tab render the
// public Work view (dated, curated snapshot). Private builds are unchanged. ──
if (process.env.FOCUSA_PUBLIC_NEWTAB === '1') {
  await writeFile(resolve(dist, 'public-newtab.html'),
    '<!doctype html><meta http-equiv="refresh" content="0; url=startpage.html?public-work=1">\n');
  const distManifest = JSON.parse(await readFile(resolve(dist, 'manifest.json'), 'utf8'));
  distManifest.chrome_url_overrides = { newtab: 'public-newtab.html' };
  await writeFile(resolve(dist, 'manifest.json'), `${JSON.stringify(distManifest, null, 2)}\n`);
  console.log('PASS: default new tab points at the public Work view (FOCUSA_PUBLIC_NEWTAB=1)');
}
